export let warrior = {
  "arms": {
        "image": "background-warrior-arms.png",
        "total": 0,
        "max": 60,
        "talents": [
          {
                "name": "Improved Heroic Strike",
                "description": "Reduces the cost of your Heroic Strike ability by %p rage point(s).",
                "values": {
                    "%p": 1
                },
                "id": 0,
                "max": 3,
                "current": 0,
                "image": "ability_rogue_ambush.png"
            },
          {
                "name": "Deflection",
                "description": "Increases your Parry chance by %p%.",
                "values": {
                    "%p": 1
                },
                "id": 1,
                "row": 0,
                "col": 1,
                "max": 5,
                "current": 0,
                "image": "ability_parry.png"
            },
          {
                "name": "Improved Rend",
                "description": "Increases the bleed damage done by your Rend ability by %p%.",
                "values": {
                    "%p": 25
                },
                "id": 2,
                "row": 0,
                "col": 2,
                "max": 3,
                "current": 0,
                "image": "ability_gouge.png"
            },


          {
                "name": "Improved Charge",
                "description": "Increases the amount of rage generated by your Charge ability by %p.",
                "values": {
                    "%p": 3
                },
                "id": 3,
                "row": 1,
                "col": 0,
                "max": 2,
                "current": 0,
                "image": "ability_warrior_charge.png"
            },
          {
                "name": "Iron Will",
                "description": "Increases your chance to resist Stun and Charm effects by an additional %p%.",
                "values": {
                    "%p": 3
                },
                "id": 4,
                "row": 1,
                "col": 1,
                "max": 5,
                "current": 0,
                "image": "spell_magic_magearmor.png"
            },
          {
                "name": "Improved Thunder Clap",
                "description": "Reduces the cost of your Thunder Clap by %p rage point and increases the damage by %d% and the slowing effect by an additional %s%.",
                "values": {
                    "%p": 1,
                    "%d": 40,
                    "%s": 4
                },
                "id": 5,
                "row": 1,
                "col": 2,
                "max": 3,
                "current": 0,
                "image": "ability_thunderclap.png"
            },


          {
                "name": "Improved Overpower",
                "description": "Increase the critical strike chance of your Overpower ability by %p%.",
                "values": {
                    "%p": 25
                },
                "id": 6,
                "row": 2,
                "col": 0,
                "max": 2,
                "current": 0,
                "image": "inv_sword_05.png"
            },
          {
                "name": "Anger Management",
                "description": "Generates %p rage per 3 seconds while in combat.",
                "values": {
                    "%p": 1
                },
                "id": 7,
                "row": 2,
                "col": 1,
                "max": 1,
                "current": 0,
                "image": "spell_holy_blessingofstamina.png"
            },
          {
                "name": "Deep Wounds",
                "description": "Your critical strikes cause the opponent to bleed, dealing %p% of your melee weapon's average damage over 12 seconds.",
                "values": {
                    "%p": 20
                },
                "id": 8,
                "row": 2,
                "col": 2,
                "max": 3,
                "current": 0,
                "image": "ability_backstab.webp"
            },


          {
                "name": "Two-Handed Weapon Specialization",
                "description": "Increases the damage you deal with two-handed melee weapons by %p%.",
                "values": {
                    "%p": 1
                },
                "id": 9,
                "row": 3,
                "col": 1,
                "max": 5,
                "current": 0,
                "image": "inv_axe_09.webp"
            },
          {
                "name": "Impale",
                "description": "Increases the critical strike damage bonus of your abilities in Battle, Defensive and Berserker stance by %p%.",
                "values": {
                    "%p": 10
                },
                "id": 10,
                "row": 3,
                "col": 2,
                "max": 2,
                "current": 0,
                "image": "ability_searingarrow.png"
            },
          {
                "name": "Improved Slam",
                "description": "Decreases the casting time of your Slam ability by %p sec.",
                "values": {
                    "%p": 0.5
                },
                "id": 11,
                "row": 3,
                "col": 3,
                "max": 2,
                "current": 0,
                "image": "ability_warrior_decisivestrike.webp"
            },


          {
                "name": "Poleaxe Specialization",
                "description": "Increases your chance to get a critical strike with Axes and Polearms by %p%.",
                "values": {
                    "%p": 1
                },
                "id": 12,
                "row": 4,
                "col": 0,
                "max": 5,
                "current": 0,
                "image": "inv_axe_06.png"
            },
          {
                "name": "Sweeping Strikes",
                "description": "Your next %p melee attacks strike an additional nearby opponent.",
                "values": {
                    "%p": 10
                },
                "id": 13,
                "row": 4,
                "col": 1,
                "max": 1,
                "current": 0,
                "image": "ability_rogue_slicedice.png",
                "type": "ability"
            },
          {
                "name": "Mace Specialization",
                "description": "Gives your melee attacks a chance to stun your target for 3 seconds and generate %p rage when using a mace.",
                "values": {
                    "%p": 7
                },
                "id": 14,
                "row": 4,
                "col": 2,
                "max": 5,
                "current": 0,
                "image": "inv_mace_01.webp"
            },
          {
                "name": "Sword Specialization",
                "description": "Gives you a %p% chance to get an extra attack on the same target after hittin your target with your Sword.",
                "values": {
                    "%p": 1
                },
                "id": 15,
                "row": 4,
                "col": 3,
                "max": 5,
                "current": 0,
                "image": "inv_sword_27.png"
            },


          {
                "name": "Improved Intercept",
                "description": "Reduces the cooldown of your Intercept ability by %p sec.",
                "values": {
                    "%p": 5
                },
                "id": 16,
                "row": 5,
                "col": 0,
                "max": 2,
                "current": 0,
                "image": "ability_warrior_victoryrush.webp"
            },
          {
                "name": "Improved Hamstring",
                "description": "Gives your Hamstring ability a %p% chance to immobilize the target for 5 seconds.",
                "values": {
                    "%p": 2
                },
                "id": 17,
                "row": 5,
                "col": 2,
                "max": 3,
                "current": 0,
                "image": "ability_shockwave.webp"
            },
          {
                "name": "Improved Disiplines",
                "description": "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by %p min and increases their duration by %s sec.",
                "values": {
                    "%p": 4,
                    "%s": 2
                },
                "id": 18,
                "row": 5,
                "col": 3,
                "max": 3,
                "current": 0,
                "image": "ability_warrior_improveddisciplines.webp"
            },


          {
                "name": "Blood Frenzy",
                "description": "Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by %p%.",
                "values": {
                    "%p": 2
                },
                "id": 19,
                "row": 6,
                "col": 0,
                "max": 2,
                "current": 0,
                "image": "ability_warrior_bloodfrenzy.webp"
            },
          {
                "name": "Mortal Strike",
                "description": "A viscious strike that deals weapon damage plus %p and wounds the target, reducing the effectiveness of any healing by 50% for 10 seconds.",
                "values": {
                    "%p": 88
                },
                "id": 20,
                "row": 6,
                "col": 1,
                "max": 1,
                "current": 0,
                "image": "ability_warrior_savageblow.png",
                "type": "ability"
            },
          {
                "name": "Second Wind",
                "description": "Whenever you are struck by a Stun or Immobilize effect you will generate %r rage and %p% of your total health over 10 seconds.",
                "values": {
                    "%p": 5,
                    "%r": 10
                },
                "id": 21,
                "row": 6,
                "col": 2,
                "max": 2,
                "current": 0,
                "image": "ability_hunter_harass.png"
            },


          {
                "name": "Endless Rage",
                "description": "You generate %p% more rage from damage dealt.",
                "values": {
                    "%p": 8
                },
                "id": 22,
                "row": 7,
                "col": 1,
                "max": 3,
                "current": 0,
                "image": "ability_warrior_endlessrage.png"
            },
          {
                "name": "Empowered Rend",
                "description": "The damage dealt by Rend is %p seconds faster.",
                "values": {
                    "%p": 0.5
                },
                "id": 23,
                "row": 7,
                "col": 2,
                "max": 2,
                "current": 0,
                "image": "ability_gouge.png"
            },


          {
                "name": "Bladestorm",
                "description": "Instantly Whirlwind up to 4 nearby targets and for thr next 6 seconds you will perform a whirlwind attack every 1 sec. <br> While under the effects of Bladestorm, you can move but cannot perform any other abilities but you do not feel pity or remorse or fear, you cannot be stopped unless killed, and your movement speed cannot be reduced below 60%.",
                "values": {},
                "id": 24,
                "row": 8,
                "col": 1,
                "max": 1,
                "current": 0,
                "image": "ability_warrior_bladestorm.png",
                "type": "ability"
            },
        ]
      },
      "fury": {
        "image": "background-warrior-fury.png",
        "total": 0,
        "max": 60,
        "talents": [
          {
                "name": "Cruelty",
                "description": "Increases your chance to get a critical strike with melee weapons by %p%.",
                "values": {
                    "%p": 1
                },
                "id": 0,
                "row": 0,
                "col": 2,
                "max": 5,
                "current": 0,
                "image": "ability_rogue_eviscerate.png"
            },
          {
                "name": "Booming Voice",
                "description": "Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by %p%.",
                "values": {
                    "%p": 10
                },
                "id": 1,
                "row": 0,
                "col": 1,
                "max": 5,
                "current": 0,
                "image": "spell_nature_purge.png"
            },


          {
                "name": "Improved Demoralizing Shout",
                "description": "Increases the melee attack power reduction of your Demoralizing Shout by %p%.",
                "values": {
                    "%p": 8
                },
                "id": 2,
                "row": 1,
                "col": 1,
                "max": 5,
                "current": 0,
                "image": "ability_warrior_warcry.webp"
            },
          {
                "name": "Unbridled Wrath",
                "description": "Gives you a chance to generate an additional %p rage point(s) when you deal melee damage with a weapon.",
                "values": {
                    "%p": 1
                },
                "id": 3,
                "row": 1,
                "col": 2,
                "max": 5,
                "current": 0,
                "image": "spell_nature_stoneclawtotem.png"
            },


          {
                "name": "Blood Craze",
                "description": "Regenerates %p% of your total Health over 6 seconds after being the victim of a critical strike.",
                "values": {
                    "%p": 1
                },
                "id": 4,
                "row": 2,
                "col": 2,
                "max": 3,
                "current": 0,
                "image": "spell_shadow_summonimp.png"
            },
          {
                "name": "Piercing Howl",
                "description": "Causes all enemies within 10 yards to be Dazed, reducing movement speed by %p% for 6 seconds.",
                "values": {
                    "%p": 50
                },
                "id": 5,
                "row": 2,
                "col": 1,
                "max": 1,
                "current": 0,
                "image": "spell_shadow_deathscream.png",
                "type": "ability"
            },
          {
                "name": "Improved Cleave",
                "description": "Increases the bonus damage done by your Cleave ability by %p%.",
                "values": {
                    "%p": 40
                },
                "id": 6,
                "row": 2,
                "col": 0,
                "max": 3,
                "current": 0,
                "image": "ability_warrior_cleave.png"
            },
          {
                "name": "Commanding Presence",
                "description": "Increases the melee Attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by %p%.",
                "values": {
                    "%p": 3
                },
                "id": 7,
                "row": 2,
                "col": 3,
                "max": 5,
                "current": 0,
                "image": "spell_nature_focusedmind.png"
            },


          {
                "name": "Dual Wield Specialization",
                "description": "Increases the damage done by your offhand weapon by %p%.",
                "values": {
                    "%p": 5
                },
                "id": 8,
                "row": 3,
                "col": 1,
                "max": 5,
                "current": 0,
                "image": "ability_dualwield.png"
            },
          {
                "name": "Enrage",
                "description": "Gives you a %p% melee damage bonus for 12 seconds up to a maximum of 12 swings after being the victim of a critical strike.",
                "values": {
                    "%p": 5
                },
                "id": 9,
                "row": 3,
                "col": 2,
                "max": 5,
                "current": 0,
                "image": "spell_shadow_unholyfrenzy.webp"
            },


          {
                "name": "Improved Execute",
                "description": "Reduces the rage cost of your Execute ability by %p.",
                "values": {
                    "%p": 2
                },
                "id": 10,
                "row": 4,
                "col": 0,
                "max": 2,
                "current": 0,
                "image": "inv_sword_48.png"
            },
          {
                "name": "Death Wish",
                "description": "When activated, increases your physical damage by %p% and makes you immune to Fear effects, but increases all damage taken by 5%. Lasts 30 seconds.",
                "values": {
                    "%p": 20
                },
                "id": 11,
                "row": 4,
                "col": 1,
                "max": 1,
                "current": 0,
                "image": "spell_shadow_deathpact.webp",
                "type": "ability"
            },
          {
                "name": "Weapon Mastery",
                "description": "Reduces the chance for your attacks to be dodged by %p% and reduces the duration of all Disarm effects used against you by %d.<br> This does not stack with other Disarm duration reducing effects.",
                "values": {
                    "%p": 2,
                    "%d": 25
                },
                "id": 12,
                "row": 4,
                "col": 3,
                "max": 2,
                "current": 0,
                "image": "ability_warrior_weaponmastery.webp"
            },


          {
                "name": "Improved Berserker Rage",
                "description": "The Berserker Rage ability will generate %p rage when used.",
                "values": {
                    "%p": 10
                },
                "id": 13,
                "row": 5,
                "col": 0,
                "max": 2,
                "current": 0,
                "image": "spell_nature_ancestralguardian.webp"
            },
          {
                "name": "Flurry",
                "description": "Increases your attack speed by %p% for your next 3 swings after dealing a melee critical strike.",
                "values": {
                    "%p": 5
                },
                "id": 14,
                "row": 5,
                "col": 2,
                "max": 5,
                "current": 0,
                "image": "ability_ghoulfrenzy.png"
            },


          {
                "name": "Precision",
                "description": "Increases your chance to hit with melee weapons by %p%.",
                "values": {
                    "%p": 1
                },
                "id": 15,
                "row": 6,
                "col": 0,
                "max": 3,
                "current": 0,
                "image": "ability_marksmanship.webp"
            },
          {
                "name": "Bloodlust",
                "description": "Instantly attack the target causing %p damage. In addition, the next 5 successful melee attacks will restore 10 health.<br> This effect lasts 8 seconds. Damage is based on your attack power.",
                "values": {
                    "%p": 45
                },
                "id": 16,
                "row": 6,
                "col": 1,
                "max": 1,
                "current": 0,
                "image": "spell_nature_bloodlust.png",
                "type": "ability"
            },
          {
                "name": "Improved Whirlwind",
                "description": "Reduces the cooldown of your Whirlwind ability by %p sec.",
                "values": {
                    "%p": 1
                },
                "id": 17,
                "row": 6,
                "col": 2,
                "max": 2,
                "current": 0,
                "image": "ability_whirlwind.webp"
            },


          {
                "name": "Improved Berserker Stance",
                "description": "Increases attack power by %p% and reduces threat caused by %p% while in Berserker Stance.",
                "values": {
                    "%p": 2
                },
                "id": 18,
                "row": 7,
                "col": 2,
                "max": 5,
                "current": 0,
                "image": "ability_racial_avatar.png"
            },


          {
                "name": "Rampage",
                "description": "Warrior goes on a rampage, increasing attack power by %p and causeing most successful melee attacks to increase attack power by an additional 30.<br> This effect will stack up to 5 times. Lasts 30 seconds. This ability can only be used after scoring a critical hit.",
                "values": {
                    "%p": 30
                },
                "id": 19,
                "row": 8,
                "col": 1,
                "max": 1,
                "current": 0,
                "image": "ability_warrior_rampage.png",
                "type": "ability"
            },
        ]
      },
      "protection": {
        "image": "background-warrior-protection.png",
        "total": 0,
        "max": 60,
        "talents": [
          {
            "name": "Improved Bloodrage",
            "description": "Increases the instant rage generated by yor Bloodrage ability %p.",
            "values": {
                "%p": 3
            },
            "id": 0,
            "row": 0,
            "col": 0,
            "max": 2,
            "current": 0,
            "image": "ability_racial_bloodrage.png"
          },
          {
            "name": "Tactical Mastery",
            "description": "You retain up to an additional %p of your rage points when you change stances.<br> Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance.",
            "values": {
                "%p": 5
            },
            "id": 1,
            "row": 0,
            "col": 1,
            "max": 3,
            "current": 0,
            "image": "spell_nature_enchantarmor.webp"
          },
          {
            "name": "Anticipation",
            "description": "Increases your Defense skill by %p.",
            "values": {
                "%p": 4
            },
            "id": 2,
            "row": 0,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "spell_nature_mirrorimage.png"
          },


          {
            "name": "Shield Specialization",
            "description": "Increases your chance to block attacks by %p% and has a %c% chance to generate 1 rage when a block occurs.",
            "values": {
                "%p": 1,
                "%c": 20
            },
            "id": 3,
            "row": 1,
            "col": 1,
            "max": 5,
            "current": 0,
            "image": "inv_shield_06.png"
          },
          {
            "name": "Toughness",
            "description": "Increases your armor value from items by %p%.",
            "values": {
                "%p": 2
            },
            "id": 4,
            "row": 1,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "spell_holy_devotion.png"
          },


          {
            "name": "Last Stand",
            "description": "When activated, this ability temporarily grants %p% of your maximum health for 20 seconds. After the effect expires, the health is lost.",
            "values": {
                "%p": 2
            },
            "id": 5,
            "row": 2,
            "col": 0,
            "max": 1,
            "current": 0,
            "image": "spell_holy_ashestoashes.png",
            "type": "ability"
          },
          {
            "name": "Improved Shield Block",
            "description": "Allows your Shield Block ability to block an additional attack and increases the duration by %p second.",
            "values": {
                "%p": 1
            },
            "id": 6,
            "row": 2,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "ability_defend.png"
          },
          {
            "name": "Improved Revenge",
            "description": "Gives your Revenge ability a %p% chance to stun the target for 3 seconds.",
            "values": {
                "%p": 15
            },
            "id": 7,
            "row": 2,
            "col": 2,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_revenge.webp"
          },
          {
            "name": "Defiance",
            "description": "Increases the threat generated by your attack by %p% while in Defensive Stance and rduces your chance to be dodged or parried by %c%.",
            "values": {
                "%p": 2,
                "%c": 0.5
            },
            "id": 8,
            "row": 2,
            "col": 3,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_innerrage.png"
          },


          {
            "name": "Improved Sunder Armor",
            "description": "Reduces the cost of your Sunder Armor and Devestate abilities by %p rage point.",
            "values": {
                "%p": 1
            },
            "id": 9,
            "row": 3,
            "col": 0,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_sunder.png"
          },
          {
            "name": "Imporved Disarm",
            "description": "Increases the duration of your Disarm ability by %p sec(s).",
            "values": {
                "%p": 1
            },
            "id": 10,
            "row": 3,
            "col": 1,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_disarm.png"
          },
          {
            "name": "Improved Taunt",
            "description": "Reduced the cooldown of your Taunt ability by %p sec alongside increasing the range by 7 yards.",
            "values": {
                "%p": 2
            },
            "id": 11,
            "row": 3,
            "col": 2,
            "max": 2,
            "current": 0,
            "image": "spell_nature_reincarnation.png"
          },


          {
            "name": "Improved Shield Wall",
            "description": "Increases the effect duration of your Shield Wall ability by %p secs.",
            "values": {
                "%p": 3
            },
            "id": 12,
            "row": 4,
            "col": 0,
            "max": 2,
            "current": 0,
            "image": "ability_warrior_shieldwall.png"
          },
          {
            "name": "Concussion Blow",
            "description": "Stuns the opponent for %p seconds.",
            "values": {
                "%p": 5
            },
            "id": 13,
            "row": 4,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "ability_thunderbolt.png"
          },
          {
            "name": "Improved Shield Bash",
            "description": "Gives your Shield Bash ability a %p% chance to silence the target for 3 seconds.",
            "values": {
                "%p": 50
            },
            "id": 14,
            "row": 4,
            "col": 2,
            "max": 2,
            "current": 0,
            "image": "ability_warrior_shieldbash.png"
          },


          {
            "name": "Shield Mastery",
            "description": "Increases the amount of damage absorbed by your shield by %p%.",
            "values": {
                "%p": 10
            },
            "id": 15,
            "row": 5,
            "col": 0,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_shieldmastery.webp"
          },
          {
            "name": "One-Handed Weapon Specialization",
            "description": "Increases physical damage you deal when a one-handed melee weapon is equipped by %p%.",
            "values": {
                "%p": 2
            },
            "id": 16,
            "row": 5,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "inv_sword_20.png"
          },


          {
            "name": "Improved Defensive Stance",
            "description": "Reduces all spell damage taken while in Defensive Stance by %p%.",
            "values": {
                "%p": 2
            },
            "id": 17,
            "row": 6,
            "col": 0,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_defensivestance.webp"
          },
          {
            "name": "Shield Slam",
            "description": "Slam the target with your shield, causing %p damage, modified by your shield block value and dispels 1 magic effect on the target.<br> Also causes a high amount of threat.",
            "values": {
                "%p": 225
            },
            "id": 18,
            "row": 6,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "inv_shield_05.png",
            "type": "ability"
          },
          {
            "name": "Focused Rage",
            "description": "Reduces the rage cost of your offensive abilities by %p.",
            "values": {
                "%p": 1
            },
            "id": 19,
            "row": 6,
            "col": 2,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_focusedrage.png"
          },


          {
            "name": "Vitality",
            "description": "Increases your total Stamina by %p% and your total Strength by %s%.",
            "values": {
                "%p": 1,
                "%s": 2
            },
            "id": 20,
            "row": 7,
            "col": 1,
            "max": 5,
            "current": 0,
            "image": "inv_helmet_21.webp"
          },


          {
            "name": "Devestate",
            "description": "Sunder the target's armor causing the Sunder Armor effect.<br> In addition, causes %p% of weapon damage plus 15 for each application of Sunder Armor on the target. <br> The Sunder Armor effect can stack up to 5 times.",
            "values": {
                "%p": 50
            },
            "id": 21,
            "row": 8,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "inv_sword_11.png",
            "type": "ability"
          },
        ]
      },
};
